name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src-tauri

    steps:
    - uses: actions/checkout@v4

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf \
                                libgdk-pixbuf2.0-dev libatk1.0-dev
    - name: Set PKG_CONFIG_PATH for Linux
      if: matrix.os == 'ubuntu-22.04'
      run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV

    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --verbose
